# Site settings
title: Dunedin Street Art Festival
email: info@dudstreetfest.co.nz
description: "All about the Dunedin Street Art Festival, a yearly celebration of street culture in the glorious warehouse precinct."
baseurl: ""
url: "http://dudstreetfest.github.io"
twitter_username: dudstreetfest
facebook_username: dunedinstreetart

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['vendor']